l_english:
 DIVISION_QUEUED:0 "$N$ 사단"
 DIVISIONS_QUEUED:0 "$N$ 사단"
 CONVEYOR_EQUIPMENT_NEED:0 "필요 장비:"
 CONVEYOR_MANPOWER_NEED:0 "필요 인력: $AMOUNT|H$"
 DEPLOYMENT_REQUIREMENT:0 "$NAME$: $AMOUNT$"
 DEPLOYMENT_DIVISION_LABEL:0 "사단"
 DEPLOYMENT_PROGRESS_LABEL:0 "진행도"
 DEPLOYMENT_PRIORITY_LABEL:0 "우선 순위"
 DEPLOYMENT_DEPLOY_LABEL:0 "배치"
 DEPLOYMENT_TEMPLATE_ITEM_ADD:0 "§G클릭으로 배치 대기열에 추가§!"
 DEPLOYMENT_TEMPLATE_ITEM_COPY:0 "§G클릭으로 배치 가능 편제 복사§!"
 DEPLOYMENT_TEMPLATE_ITEM_EDIT:0 "§G클릭으로 사단 편제 편집§!"
 DEPLOYMENT_TRAINING:0 "훈련: $VALUE|%Y0$ $MAXVALUE|$"
 DEPLOYMENT_TRAINING_MAXVALUE_DESC:0 "/ $VALUE|H%0$ ( 배치병력의 최대 경험치는 장비의 양에 따라 달라집니다. )"
 DEPLOYMENT_CURRENT_LEVEL:0 "현재 병력 배치의 수준은 다음과 같습니다 $NUMBER$ ( $LEVEL|%Y0$ )"
 DEPLOYMENT_MANPOWER_DESC:0 "인력: $VALUE|Y0$ ( 최대 $MAX|Y0$ )"
 DEPLOYMENT_EXPERIENCE_DESC:0 "\n훈련이 완료될 시, 이 병력은 다음과 같은 수준으로 배치될 것입니다. $NUMBER$ ( $MAXLEVEL|%Y0$ ) giving it a combat modifier of $EFFECT|+=%0$"
 DEPLOYMENT_EXPERIENCE_ESTIMATED_DESC:0 "\n 이 부대가 완전히 충원된 상태라면 §Y$DATE$§!에 훈련이 완료됩니다"
 DEPLOYMENT_EQUIPMENT:0 "장비: $VALUE|%Y0$"
 DEPLOYMENT_EQUIPMENT_FULL_DESC:0 "$NAME$: $VALUE|G0$/$MAX|G0$"
 DEPLOYMENT_EQUIPMENT_DESC:0 "$NAME$: $VALUE|Y0$/$MAX|Y0$"
 DEPLOYMENT_DESIGNER:0 "사단 설계"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT:0 "        $NAME|Y$: $VALUE|Y0$"
 DEPLOYMENT_EQUIPMENT_VARIANT_AMOUNT_FULL:0 "        $NAME|G$: $VALUE|G0$"
 DEPLOYMENT_EQUIPMENT_CHANGE:0 "$NAME$: $VALUE$"
 DEPLOYMENT_ADD_TEMPLATE:0 "훈련"
 DEPLOYMENT_LINES_HIT_THE_CAP:0 "우리는 최대  $CAP|*H$ 만큼의 인원을 훈련시킬수 있습니다.\n배치가능한 최대 인력 수치 ( $RATIO|H0%$ of $INFIELD|*H$. Minimum: $MINPOSSIBLE|*H$ men)"
 REGIMENTS_SELECTION_CANCEL:0 "뒤로"
 ONLY_ONE_TEMPLATE_LEFT:0 "마지막 남은 편제를 삭제할 수 없습니다."
 DELETE_TEMPLATE:0 "목록에 있는 편제를 §R삭제§!합니다."
 DELETE_TEMPLATE_TITLE:0 "편제 삭제"
 DELETE_TEMPLATE_DESC:0 "정말로 이 편제를 삭제하시겠습니까?"
 DEPLOYMENT_REMOVE_DIVISION:0 "사단 취소"
 DEPLOYMENT_DEPLOYMENT_LABEL:0 "모병 & 배치"
 DEPLOYMENT_NOT_ALLOWED_REASON_EQUIPMENT:0 "장비가 갖춰지지 않은 병력을 §R배치§!할 수 없습니다.\n장비가 갖춰질 때 까지 기다려 주세요."
 DEPLOYMENT_NOT_ALLOWED_REASON_MANPOWER:0 "인력이 없는 병력은 §R배치§!할 수 없습니다."
 DEPLOYMENT_NOT_ALLOWED_REASON_TRAINING:0 "최소 $VALUE|1H%$ 이상 훈련을 받지 않으면 §R배치§!할 수 없습니다. (현재 $CURRENT|1R%$)"
 DEPLOYMENT_NOT_ALLOWED_REASON_SPECIAL_FORCES:0 "특수부대 한도를 넘기 때문에 병력을 §R배치§! 할 수 없습니다."
 DEPLOYMENT_HOW_TO_DESC:0 "목록에서 배치할 병력을 선택한 후 지도 상에서 배치를 원하는 지역을 §G클릭§!하세요.\n§g장비가 다 갖춰지지 않은 병력은 증원 요청을 통해 보충됩니다.\n너무 빨리 배치될 경우 적합한 훈련을 받지 못한다는 점을 기억하세요.§!"
 REINFORCEMENT:0 "충원"
 REINFORCEMENT_DESC:0 "§T활동 중인 부대에 배치 대기열 및 업그레이드와 비교할 보급될 장비의 우선순위를 설정합니다.§!"
 REINFORCEMENT_EMPTY:0 "§G현재 장비필요 요청이 없습니다.§!"
 UPGRADES:0 "업그레이드"
 group_infantry_title:0 "보병 대대"
 group_mobile_title:0 "기동 대대"
 group_armor_title:0 "기갑 대대"
 group_support_title:1 "지원 중대"
 NEW_GROUP_ADDITIONAL_COST:0 "추가 비용 $VALUE|H0$£army_experience£"
 UPGRADES_DESC:0 "§T활동 중인 부대에 업그레이드를 하기 위해 배치 대기열 및 충원과 비교할 우선순위를 설정합니다.§!"
 UPGRADES_EMPTY:0 "§G현재 업그레이드가 필요하지 않습니다.§!"
 TIMED_ACTIVITY_TITLE:0 "$NAME$은 $COUNTRY$과 적대중입니다."
 TIMED_ACTIVITY_ALERT_TITLE:0 "$NAME|H$ 은 $COUNTRY|H$과 적대중입니다"
 TIMED_ACTIVITY_ENTRY_DESC:0 "§T이 외교적 활동은 장비들을 우선적으로 지원할 것입니다.§!"
 TIMED_ACTIVITY_ENTRY_COMPLETE_DESC:0 "§G장비가 최대로 쌓였습니다.§!"
 LAND_DEPLOYMENT:0 "§T육군 배치§!"
 AIR_DEPLOYMENT:0 "§T공군 배치§!"
 NAVAL_DEPLOYMENT:0 "§T해군 배치§!"
 DIVISION_DESIGNER_RENAME:0 "이름 변경"
 DIVISION_DESIGNER_UPDATE:0 "갱신"
 DEPLOY:0 "배치"
 EDIT:0 "편집"
 VIEW:0 "보기"
 COPY:0 "복사"
 DIVISION_EQUIPMENT:1 "장비"
 DIVISION_EQUIPMENT_LONG:1 "장비 목록"
 NEW_EQUIPMENT_ALLOWED:0 "새로운 장비 사용"
 DO_NOT_CONTAINS_TEMPLATE:0 "§R이 편제는 삭제할 수 없습니다. 나라에 이 편제가 사용되는것이 없어야 합니다.§!"
 HAS_ARMIES_WITH_TEMPLATE:0 "§R$AMOUNT|H$개의 사단이 이 편제를 사용하고 있어 삭제할 수 없습니다.§!"
 HAS_ARMIES_WITH_OLD_TEMPLATE:0 "§R$AMOUNT|H$ 사단이 이 전 편제에서 새 편제로 전환 도중에 (새 편제에서 사용하는 장비의 배치 대기 상태)이 편제를 삭제할 수 없습니다. §!"
 HAS_DEPLOYMENT_CONVEYORS_WITH_TEMPLATE:0 "해당 편제로 $AMOUNT|H$ 만큼 생산하고 있어 §R삭제§!할 수 없습니다."
 DEPLOYMENT_TEMPLATE_LABEL:0 "편제"
 TEMPLATE_PRIO_0:0 "예비"
 TEMPLATE_PRIO_0_DESC:0 "이 편제로 지정된 병력은 배치되면 장비를 가장 나중에 보급받으며 충원에 있어 가장 낮은 우선순위를 지닙니다. 기지를 지킬 목적 등으로 사용될 병력에 적합합니다."
 TEMPLATE_PRIO_1:0 "기본"
 TEMPLATE_PRIO_1_DESC:0 "이 편제로 지정된 병력은 배치되면 일반적인 우선순위로 보급 및 증원이 이루어집니다."
 TEMPLATE_PRIO_2:0 "정예"
 TEMPLATE_PRIO_2_DESC:0 "이 편제로 지정된 병력은 배치되면 최우선으로 장비를 보급받게 됩니다. 당신의 정예 부대와 그들이 활약할 수 있는 곳에 적합합니다."
 DEPLOYMENT_LEND_LEASE_COUNTRY:0 "무기 대여: $COUNTRY$"
 ADD_CONVEYOR_LINE_BUTTON_LABEL:0 "부대 추가"
 ADD_CONVEYOR_LINE_BUTTON_DESC:0 "병렬로 생산될 $CONVEYOR|H$ 병력을 추가합니다. \n\n§GShift + 클릭§! 라인 5개 추가합니다."
 CONVEYOR_GENERIC_NAME_EDIT_DESC:0 "여기에 입력해서 배치되는 범용이름을 변경할 수 있습니다."
 CONVEYOR_TEMPLATE_ICON_DESC:0 "이 배치에는 $TEMPLATE|H$ 편제를 사용하는 사단을 생성합니다."
 CANCEL_CONVEYOR_TOOLTIP:0 "모든 배치 라인을 §R취소§!합니다."
 DEPLOY_CONVEYOR_TOOLTIP:0 "§G클릭§! 모든 라인을 즉시 배치합니다."
 DEPLOY_CONVEYOR_DISABLED_TOOLTIP:0 "§R배치§! 준비가 되었지만 배치되지 않았습니다."
 CONVEYOR_CANCEL_TITLE:0 "배치를 §R취소§!"
 CONVEYOR_CANCEL_DESC:0 "정말 모든 배치 라인을 §R 취소§! 하시겠습니까?"
 CONVEYOR_LINE_CANCEL_DESC:0 "이 라인의 생산을 §R취소§!"
 CONVEYOR_LINE_CANCEL_ACCEPT_TITLE:0 "배치 라인을 §R취소§!"
 CONVEYOR_LINE_CANCEL_ACCEPT_SINGLE_DESC:0 "정말이 배치 라인을 §R취소§! 하시겠습니까? \n(배치된 병력도 §R삭제§!됩니다)"
 CONVEYOR_LINE_CANCEL_ACCEPT_DESC:0 "정말이 배치 라인을 §R취소 §! 하시겠습니까?"
 CONVEYOR_GROUP_ASSIGN_DESC:0 "§G클릭§!로 배치하도록 지시합니다. \n§G우클릭§! 배치를 재설정합니다."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_ORDERS_DESC:0 "배치를 그룹에 할당하기 위해서는 전구에서 적어도 하나의 지령을 가지고 있어야합니다."
 CONVEYOR_GROUP_CAN_NOT_ASSIGN_NO_LOCATION_DESC:0 "배치를 그룹에 할당하려면 목표 지점을 가지고 있어야합니다."
 CONVEYOR_SET_LOCATION_DESC:0 "§G클릭§!으로 이 병력의 배치 장소를 지정합니다.\n§G우클릭§!으로 초기화"
 CONVEYOR_SET_COLONIAL_LOCATION_DESC:0 "§G클릭§!으로 배치하기 위한 위치를 지정하세요.\n§G우클릭§!으로 위치를 초기화.\n§Y이것은 식민지 편제이며 본국에서만 배치가 가능합니다!§!"
 CONVEYOR_SET_LOCATION_NOT_SET:0 "§S위치 미설정§!"
 CONVEYOR_LINE_PREFIX_NAME_EDIT_DESC:0 "여기를 변경하여 현재 라인의 접두사를 변경할 수 있습니다."
 CONVEYOR_LINE_DEPLOY_DESC:0 "§G클릭§!으로 이 라인을 즉시 배치합니다."
 CONVEYOR_SERIES_INCREASE_DESC:0 "병렬적으로 훈련시킬 경우 각각 별도로 훈련이 이루어집니다.\n\n무한 생산을 택할 경우, 해당 사단의 훈련이 완료되면 새 사단을 훈련하게 됩니다."
 CONVEYOR_SERIES_AMOUNT_DESC:0 "이것은 종료까지 각 라인에서 훈련이 이루어지는 사단의 수입니다. \n\n무한으로 설정하면 이전 사단의 배치가 완료 될 때마다 새로운 사단의 훈련을 시작합니다."
 CONVEYOR_SERIES_DECREASE_DESC:0 "사단의 훈련이 끝날 때마다 각 열의 숫자가 줄어듭니다. \n\n무한으로 설정하면 이전 사단의 배치가 완료 할 때마다 새로운 사단의 훈련을 시작합니다."
 CONVEYOR_LOW_PRIORITY_DESC:0 "낮은 충원 우선순위."
 CONVEYOR_MEDIUM_PRIORITY_DESC:0 "중간 충원 우선순위."
 CONVEYOR_HIGH_PRIORITY_DESC:0 "높은 충원 우선순위."
 CONVEYOR_CAN_NOT_TRAIN:0 "§R훈련을 위한 장비 부족§!"
 CONVEYOR_CAN_NOT_MANPOWER_TRAIN:0 "§R훈련에 필요한 인력이 충분하지 않습니다§!"
 CONVEYOR_CAN_NOT_TRAIN_COUNT:1 "§R$DIVS|H$개 사단을 훈련하는데 필요한 인력이나 장비가 충분하지 않습니다§!"
 CONVEYOR_COLLAPSE_DESC:0 "없애기 위해 §G클릭§!"
 CONVEYOR_EXPAND_DESC:0 "추가하기 위해 §G클릭§!"
 CONVEYOR_MOVE_UP:0 "§G클릭§! 위로 올림\n§GShift+클릭§! 제일 위로 올림"
 CONVEYOR_MOVE_DOWN:0 "§G클릭§! 아래로 내림\n§GShift+클릭§! 제일 아래로 내림"
 DEPLOYMENT_LOW_PRIORITY_DESC:0 "낮은 장비보급 우선순위"
 DEPLOYMENT_MEDIUM_PRIORITY_DESC:0 "중간 장비보급 우선순위"
 DEPLOYMENT_HIGH_PRIORITY_DESC:0 "높은 장비보급 우선순위"
 UPGRADE_HIGH_PRIORITY:0 "§T높은 업그레이드 우선순위§!"
 UPGRADE_MEDIUM_PRIORITY:0 "§T중간 업그레이드 우선순위§!"
 UPGRADE_LOW_PRIORITY:0 "§T낮은 업그레이드 우선순위§!"
 CONVEYOR_HAS_BAD_LOCATION:0 "이 곳은 현재 배치하기에 §R부적합§!합니다."
 CONVEYOR_TRAINING_NOT_FINISHED:0 "해당 라인의 훈련이 아직 끝나지 않았습니다."
 CONVEYOR_SERIES_CURRENT_AMOUNT_DESC:0 "라인의 현재 연속 훈련 수."
 CONVEYOR_LINE_SERIES_BASE:0 "$CURRENT$/$TARGET$"
 DEPLOYMENT_LINE_NAME_OVERRIDE_CANCEL:0 "§H사용자 이름 지우기.§!\n이미 사용되는 이름이 아니라면, 원래 사용되는 이름으로 복원할 것입니다."
 DEPLOYMENT_LINE_CHOOSE_OTHER_NAME:0 "§H다른 역사적 이름을 선택.§!\n§G클릭§!으로 모든 역사적 이름에 대한 리스트를 여세요 . 편제를 이용해서 부대명을 변경할 수 있습니다."
 DEPLOYMENT_LINE_EDIT_NAME:0 "사용자 이름을 사용하기 위해서 §G클릭§! 하고 입력하세요."
 DEPLOYMENT_LINE_OUT_OF_NAMES:0 "§g역사적인 이름 중에서.§!"
 MISSING_SPECIAL_FORCES_CAP:0 "§R특수부대 허용량이 충분하지 않음§!"
 TRAINING_HALTED:0 "훈련이 중단되었습니다.\n"
 CANNOT_DELETE_SPECIAL_TEMPLATES:0 "특수 편제를 제거할 수 없습니다."
 DEPLOYMENT_CANNOT_TRAIN_SPECIAL_UNITS:1 "새로운 특수 편제 사단은 훈련할 수 없습니다."
 DEPLOYMENT_EXILE_WITH_NO_CAPITAL:0 "§H망명정부§! 상태에서는 새 사단을 훈련시키려면 §H수도§!를 지배해야 합니다."
 CANT_CHANGE_DUE_TO_SPECIAL_FORCES_CAP:0 "특수부대 수용 제한에 도달하여 이 편제를 변경할 수 없습니다."
 NO_SPECIAL_FORCES:0 "이 편제는 어떠한 특수부대도 포함하고 있지 않습니다"
 SPECIAL_FORCES_IN_TEMPLATE:0 "이 편제는 $NUM|Y$개의 특수부대를 포함하고 있습니다"
 SPECIAL_FORCES_CAP_DESC:0 "우리의 특수부대 허용 한계치 $CAP|Y$ 중 현재 $USED|Y$개가 배치되어 있으며 $IN_TRAINING|Y$(이)가 훈련 중입니다."
 DEPLOYMENT_MAX_DEPLOYABLE_DIVISION_FOR_TEMPLATE:0 "이 편제를 사용하는$TRAINABLE|Y$개의 사단(들)을 위해 남겨 두어야 합니다."